In [1]:
import pandas as pd
import numpy as np
import pickle

In [2]:
import pandas as pd
rating = pd.read_csv("Movie rating.csv")

In [3]:
rating

Name    Year Duration  \
0     #Gadhvi (He thought he was Gandhi) -2019.0  109 min   
1                                #Yaaram -2019.0  110 min   
2                   ...Aur Pyaar Ho Gaya -1997.0  147 min   
3                              ...Yahaan -2005.0  142 min   
4                     ?: A Question Mark -2012.0   82 min   
...                                  ...     ...      ...   
5654                              Zubaan -2015.0  115 min   
5655                            Zubeidaa -2001.0  153 min   
5656                     Zulm Ki Zanjeer -1989.0  125 min   
5657                               Zulmi -1999.0  129 min   
5658                        Zulm-O-Sitam -1998.0  130 min   

                          Genre  Rating  Votes         Director  \
0                         Drama     7.0      8    Gaurav Bakshi   
1               Comedy, Romance     4.4     35       Ovais Khan   
2        Comedy, Drama, Musical     4.7    827     Rahul Rawail   
3           Drama, Romance, War     7.4  1,086   Shoojit Sircar   
4     Horror, Mystery, Thriller     5.6    326    Allyson Patel   
...                         ...     ...    ...              ...   
5654                      Drama     6.1    408      Mozez Singh   
5655  Biography, Drama, History     6.2  1,496    Shyam Benegal   
5656       Action, Crime, Drama     5.8     44  S.P. Muthuraman   
5657              Action, Drama     4.5    655       Kuku Kohli   
5658              Action, Drama     6.2     20     K.C. Bokadia   

              Actor 1                 Actor 2           Actor 3  
0        Rasika Dugal          Vivek Ghamande     Arvind Jangid  
1             Prateik              Ishita Raj   Siddhant Kapoor  
2          Bobby Deol  Aishwarya Rai Bachchan     Shammi Kapoor  
3     Jimmy Sheirgill          Minissha Lamba    Yashpal Sharma  
4           Yash Dave          Muntazir Ahmad      Kiran Bhatia  
...               ...                     ...               ...  
5654    Vicky Kaushal         Sarah Jane Dias  Raaghavv Chanana  
5655   Karisma Kapoor                   Rekha    Manoj Bajpayee  
5656      Chiranjeevi              Jayamalini       Rajinikanth  
5657     Akshay Kumar          Twinkle Khanna       Aruna Irani  
5658       Dharmendra              Jaya Prada       Arjun Sarja  

[5659 rows x 10 columns]

In [4]:
rating.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5659 entries, 0 to 5658
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Name      5659 non-null   object 
 1   Year      5659 non-null   float64
 2   Duration  5659 non-null   object 
 3   Genre     5659 non-null   object 
 4   Rating    5659 non-null   float64
 5   Votes     5659 non-null   object 
 6   Director  5659 non-null   object 
 7   Actor 1   5659 non-null   object 
 8   Actor 2   5659 non-null   object 
 9   Actor 3   5659 non-null   object 
dtypes: float64(2), object(8)
memory usage: 442.2+ KB


In [5]:
rating.isnull().sum()

Name        0
Year        0
Duration    0
Genre       0
Rating      0
Votes       0
Director    0
Actor 1     0
Actor 2     0
Actor 3     0
dtype: int64

In [6]:
#To drop columns with Nan
#rating = rating.dropna()

In [7]:
rating

Name    Year Duration  \
0     #Gadhvi (He thought he was Gandhi) -2019.0  109 min   
1                                #Yaaram -2019.0  110 min   
2                   ...Aur Pyaar Ho Gaya -1997.0  147 min   
3                              ...Yahaan -2005.0  142 min   
4                     ?: A Question Mark -2012.0   82 min   
...                                  ...     ...      ...   
5654                              Zubaan -2015.0  115 min   
5655                            Zubeidaa -2001.0  153 min   
5656                     Zulm Ki Zanjeer -1989.0  125 min   
5657                               Zulmi -1999.0  129 min   
5658                        Zulm-O-Sitam -1998.0  130 min   

                          Genre  Rating  Votes         Director  \
0                         Drama     7.0      8    Gaurav Bakshi   
1               Comedy, Romance     4.4     35       Ovais Khan   
2        Comedy, Drama, Musical     4.7    827     Rahul Rawail   
3           Drama, Romance, War     7.4  1,086   Shoojit Sircar   
4     Horror, Mystery, Thriller     5.6    326    Allyson Patel   
...                         ...     ...    ...              ...   
5654                      Drama     6.1    408      Mozez Singh   
5655  Biography, Drama, History     6.2  1,496    Shyam Benegal   
5656       Action, Crime, Drama     5.8     44  S.P. Muthuraman   
5657              Action, Drama     4.5    655       Kuku Kohli   
5658              Action, Drama     6.2     20     K.C. Bokadia   

              Actor 1                 Actor 2           Actor 3  
0        Rasika Dugal          Vivek Ghamande     Arvind Jangid  
1             Prateik              Ishita Raj   Siddhant Kapoor  
2          Bobby Deol  Aishwarya Rai Bachchan     Shammi Kapoor  
3     Jimmy Sheirgill          Minissha Lamba    Yashpal Sharma  
4           Yash Dave          Muntazir Ahmad      Kiran Bhatia  
...               ...                     ...               ...  
5654    Vicky Kaushal         Sarah Jane Dias  Raaghavv Chanana  
5655   Karisma Kapoor                   Rekha    Manoj Bajpayee  
5656      Chiranjeevi              Jayamalini       Rajinikanth  
5657     Akshay Kumar          Twinkle Khanna       Aruna Irani  
5658       Dharmendra              Jaya Prada       Arjun Sarja  

[5659 rows x 10 columns]

In [8]:
rating.isnull().sum()

Name        0
Year        0
Duration    0
Genre       0
Rating      0
Votes       0
Director    0
Actor 1     0
Actor 2     0
Actor 3     0
dtype: int64

In [9]:
rating.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5659 entries, 0 to 5658
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Name      5659 non-null   object 
 1   Year      5659 non-null   float64
 2   Duration  5659 non-null   object 
 3   Genre     5659 non-null   object 
 4   Rating    5659 non-null   float64
 5   Votes     5659 non-null   object 
 6   Director  5659 non-null   object 
 7   Actor 1   5659 non-null   object 
 8   Actor 2   5659 non-null   object 
 9   Actor 3   5659 non-null   object 
dtypes: float64(2), object(8)
memory usage: 442.2+ KB


In [10]:
rating = rating.drop(columns=['Votes','Duration','Year'], axis = 1)

In [11]:
rating.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5659 entries, 0 to 5658
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Name      5659 non-null   object 
 1   Genre     5659 non-null   object 
 2   Rating    5659 non-null   float64
 3   Director  5659 non-null   object 
 4   Actor 1   5659 non-null   object 
 5   Actor 2   5659 non-null   object 
 6   Actor 3   5659 non-null   object 
dtypes: float64(1), object(6)
memory usage: 309.6+ KB


In [12]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
rating['Name'] = le.fit_transform(rating['Name'])

# Create a copy explicitly
rating_copy = rating.copy()

rating_copy['Name'] = le.fit_transform(rating_copy['Name'])
rating = rating_copy

unique_label = rating['Name'].unique()
print(unique_label)


[   0    1    2 ... 5382 5384 5383]


In [13]:
# Save the LabelEncoder to a pickle file
with open('label_encoder_name.pkl', 'wb') as le_file:
    pickle.dump(le, le_file)

In [14]:
le = LabelEncoder()
rating['Genre'] = le.fit_transform(rating['Genre'])
unique_label = rating['Genre'].unique()
print(unique_label)

[229 184 157 289 320  37 316 323 159 151 199 325 171 268  77   0 319 318
 269  42  50 370 142 105  75 211 260 369 133 321 193  91 183 284 214 324
 283 246  17   7 215 267  16  58  97 353 145 341 292   3 354  28 342  76
  47 348 304 288 239  19  38 277  71  27  39 245  40 262 197 367 152 210
  18 201 164 359 248 360 343 300 336 272 280  89  49 196 270  66 365 271
 274 198  70  34  14 186  46  25 131  20 244  83   6  45 109 209  87 237
 256 330  24 261  32 102  41  93 103   5   1  98 295 346 258 338 228 349
 314 334 345 136 127 313 192 134 290 180 291 241  80 187  33  35 112  48
 224 176 130 107 137  74  22 200 350  10 206  78  86 172 303 231 294 162
 110 332  43 129  44  92 286 328 375 178 372 232  90 301 202 218  60 121
 135  94 296 156 173 153 225  29 276 163  79 242  52 190  11 143 123 149
 161 220 339 250 279 113 257 144 249 170   8 166 117  88 265  65 185 305
  63 352 140 230 273  15   4  96  99 299 310 124  12 358 115 326 194 297
 148 181  95 139 335 275 150  61 100 264 221 189 11

In [15]:
# Save the LabelEncoder to a pickle file
with open('label_encoder_genre.pkl', 'wb') as le_file:
    pickle.dump(le, le_file)

In [16]:
le = LabelEncoder()
rating['Director'] = le.fit_transform(rating['Director'])
unique_label = rating['Director'].unique()
print(unique_label)

[ 629 1335 1530 ... 2244 2155 1223]


In [17]:
# Save the LabelEncoder to a pickle file
with open('label_encoder_director.pkl', 'wb') as le_file:
    pickle.dump(le, le_file)

In [18]:
le = LabelEncoder()
rating['Actor 1'] = le.fit_transform(rating['Actor 1'])
unique_label = rating['Actor 1'].unique()
print(unique_label)

[1352 1198  378 ... 1443 1732  429]


In [19]:
# Save the LabelEncoder to a pickle file
with open('label_encoder_actor 1.pkl', 'wb') as le_file:
    pickle.dump(le, le_file)

In [20]:
le = LabelEncoder()
rating['Actor 2'] = le.fit_transform(rating['Actor 2'])
unique_label = rating['Actor 2'].unique()
print(unique_label)

[2272  719   75 ... 1430 1801  754]


In [21]:
# Save the LabelEncoder to a pickle file
with open('label_encoder_actor 2.pkl', 'wb') as le_file:
    pickle.dump(le, le_file)

In [22]:
le = LabelEncoder()
rating['Actor 3'] = le.fit_transform(rating['Actor 3'])
unique_label = rating['Actor 3'].unique()
print(unique_label)

[ 319 2148 2045 ... 1592 1681 2069]


In [23]:
# Save the LabelEncoder to a pickle file
with open('label_encoder_actor 3.pkl', 'wb') as le_file:
    pickle.dump(le, le_file)

In [43]:
y = rating[['Rating']]
X = rating.drop(['Rating'], axis=1)

In [44]:
X

Name  Genre  Director  Actor 1  Actor 2  Actor 3
0        0    229       629     1352     2272      319
1        1    184      1335     1198      719     2148
2        2    157      1530      378       75     2045
3        3    289      2044      692     1112     2524
4       75    320       135     1934     1175     1013
...    ...    ...       ...      ...      ...      ...
5654  5380    229      1223     1861     1801     1615
5655  5381    133      2059      763     1619     1184
5656  5382     28      1793      406      754     1685
5657  5384     38      1025      112     2164      314
5658  5383     38       895      468      753      303

[5659 rows x 6 columns]

In [26]:
y

Rating
0        7.0
1        4.4
2        4.7
3        7.4
4        5.6
...      ...
5654     6.1
5655     6.2
5656     5.8
5657     4.5
5658     6.2

[5659 rows x 1 columns]

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
X_train

Name  Genre  Director  Actor 1  Actor 2  Actor 3
2080  1965     28      1705     1499     1619     2242
3827  3620    159       247     1330     1647      475
92      91     28      1294      220     1216      906
5171  4916    142        57      112      962      266
1623  1536    151       466      284      302     2425
...    ...    ...       ...      ...      ...      ...
3772  3567    248      1141      525     1388     1113
5191  4935    282      2103     1761     2268      991
5226  4969    354       437     1598     2115       57
5390  5128    142      2002      761     1999     1388
860    801    316      1491      373     1852      214

[3791 rows x 6 columns]

In [48]:
threshold = 5.0
y_binary = np.where(y > threshold, 1, 0)

# Flatten the target variable using ravel()
y_binary_flat = y_binary.ravel()

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y_binary_flat, test_size=0.2, random_state=42)


In [50]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(X_train,y_train)

LogisticRegression()

In [51]:
pred = logreg.predict(X_test)
pred

array([1, 1, 1, ..., 1, 1, 1])

In [52]:
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy = accuracy_score(y_test,pred) * 100
accuracy

73.67491166077738

In [53]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier()
rfc

RandomForestClassifier()

In [54]:
rfc.fit(X_train,y_train)
pred2 = rfc.predict(X_test)
accuracy_score(y_test,pred2) * 100

73.58657243816255

In [55]:
from sklearn.ensemble import GradientBoostingClassifier
gbc = GradientBoostingClassifier()
gbc.fit(X_train,y_train)

GradientBoostingClassifier()

In [56]:
pred3 = gbc.predict(X_test)
accuracy_score(y_test,pred3) * 100

73.85159010600707

In [46]:
from sklearn.linear_model import LinearRegression
linreg = LinearRegression()
linreg.fit(X_train, y_train)

LinearRegression()

In [49]:
pred4 = linreg.predict(X_test)
accuracy_score(y_test,pred3)*100

73.85159010600707

In [57]:
import pickle
with open('LinearRegression.pkl', 'wb') as model_file:
    pickle.dump(linreg, model_file)
model_file.close()

In [37]:
with open('rating.pkl', 'wb') as pickle_out:
    pickle.dump(rating, pickle_out)

# Close the files
pickle_out.close()

In [38]:
pwd

'C:\\Users\\USER\\codsoft\\Movie rating'